### ISSUE TITLE
Include build scripts

### ISSUE THREAD

**Issue by ghost** [kodejak/Hashr#1]
This apps looks like it was set up to use gradle, however all buildscripts (build.gradle, settings.gradle etc.) have been stripped. Please add them to git since they include dependency lists and information about the project structure.

**Comment by kodejak** [comment]
I'm new to Android Studio and Gradle. Please let me know if you have all files to build with the last commit.

**Comment by ghost** [comment]
Yup, works fine. Thanks for the quick fix.
